/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SurveyRouteImport } from './routes/survey'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as NavigateRouteImport } from './routes/navigate'
import { Route as MyMapRouteImport } from './routes/my-map'
import { Route as MyAnchorsRouteImport } from './routes/my-anchors'
import { Route as AnchorsRouteImport } from './routes/anchors'
import { Route as IndexRouteImport } from './routes/index'

const SurveyRoute = SurveyRouteImport.update({
  id: '/survey',
  path: '/survey',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigateRoute = NavigateRouteImport.update({
  id: '/navigate',
  path: '/navigate',
  getParentRoute: () => rootRouteImport,
} as any)
const MyMapRoute = MyMapRouteImport.update({
  id: '/my-map',
  path: '/my-map',
  getParentRoute: () => rootRouteImport,
} as any)
const MyAnchorsRoute = MyAnchorsRouteImport.update({
  id: '/my-anchors',
  path: '/my-anchors',
  getParentRoute: () => rootRouteImport,
} as any)
const AnchorsRoute = AnchorsRouteImport.update({
  id: '/anchors',
  path: '/anchors',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anchors': typeof AnchorsRoute
  '/my-anchors': typeof MyAnchorsRoute
  '/my-map': typeof MyMapRoute
  '/navigate': typeof NavigateRoute
  '/plan': typeof PlanRoute
  '/scan': typeof ScanRoute
  '/survey': typeof SurveyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anchors': typeof AnchorsRoute
  '/my-anchors': typeof MyAnchorsRoute
  '/my-map': typeof MyMapRoute
  '/navigate': typeof NavigateRoute
  '/plan': typeof PlanRoute
  '/scan': typeof ScanRoute
  '/survey': typeof SurveyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anchors': typeof AnchorsRoute
  '/my-anchors': typeof MyAnchorsRoute
  '/my-map': typeof MyMapRoute
  '/navigate': typeof NavigateRoute
  '/plan': typeof PlanRoute
  '/scan': typeof ScanRoute
  '/survey': typeof SurveyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anchors'
    | '/my-anchors'
    | '/my-map'
    | '/navigate'
    | '/plan'
    | '/scan'
    | '/survey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anchors'
    | '/my-anchors'
    | '/my-map'
    | '/navigate'
    | '/plan'
    | '/scan'
    | '/survey'
  id:
    | '__root__'
    | '/'
    | '/anchors'
    | '/my-anchors'
    | '/my-map'
    | '/navigate'
    | '/plan'
    | '/scan'
    | '/survey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnchorsRoute: typeof AnchorsRoute
  MyAnchorsRoute: typeof MyAnchorsRoute
  MyMapRoute: typeof MyMapRoute
  NavigateRoute: typeof NavigateRoute
  PlanRoute: typeof PlanRoute
  ScanRoute: typeof ScanRoute
  SurveyRoute: typeof SurveyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/survey': {
      id: '/survey'
      path: '/survey'
      fullPath: '/survey'
      preLoaderRoute: typeof SurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigate': {
      id: '/navigate'
      path: '/navigate'
      fullPath: '/navigate'
      preLoaderRoute: typeof NavigateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-map': {
      id: '/my-map'
      path: '/my-map'
      fullPath: '/my-map'
      preLoaderRoute: typeof MyMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-anchors': {
      id: '/my-anchors'
      path: '/my-anchors'
      fullPath: '/my-anchors'
      preLoaderRoute: typeof MyAnchorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anchors': {
      id: '/anchors'
      path: '/anchors'
      fullPath: '/anchors'
      preLoaderRoute: typeof AnchorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnchorsRoute: AnchorsRoute,
  MyAnchorsRoute: MyAnchorsRoute,
  MyMapRoute: MyMapRoute,
  NavigateRoute: NavigateRoute,
  PlanRoute: PlanRoute,
  ScanRoute: ScanRoute,
  SurveyRoute: SurveyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
